	tilepal 0, GRAY, BROWN, BROWN, RED, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal 0, GRAY, BROWN, ROOF, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, BROWN, BROWN, GREEN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, BROWN
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GRAY
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GRAY
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GREEN, ROOF, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, ROOF, BROWN, ROOF, ROOF, TEXT, TEXT

rept 32
	db $ff
endr

	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, WATER, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, BROWN, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, GREEN, TEXT, GREEN